Using backend: pytorch
Traceback (most recent call last):
  File "scripts/semi_supervised/learning_curve_semi.py", line 228, in <module>
    net, optimizer = get_net_and_optimizer(args, args.architecture, unsup_scale, False) # No input transformation
  File "scripts/semi_supervised/learning_curve_semi.py", line 171, in get_net_and_optimizer
    output_regressor_class=output_regressor,
NameError: name 'output_regressor' is not defined
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/semi_supervised/learning_curve_semi.py", line 237, in <module>
    train_and_test_semi_supervised(net, optimizer, train_semi, train_labeled, test_labeled, args.n_epochs)
  File "scripts/semi_supervised/learning_curve_semi.py", line 187, in train_and_test_semi_supervised
    record_interval=report)
NameError: name 'report' is not defined
Using backend: pytorch
/home/nguyenm5/anaconda3/envs/pinot/lib/python3.8/site-packages/dgl/base.py:25: UserWarning: Currently adjacency_matrix() returns a matrix with destination as rows by default.  In 0.5 the result will have source as rows (i.e. transpose=True)
  warnings.warn(msg, warn_type)
/home/nguyenm5/coding/pinot/pinot/regressors/gaussian_process_regressor.py:325: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  torch.range(0, self.y_tr_sigma_diag.shape[0] - 1)[:, None],
/home/nguyenm5/coding/pinot/pinot/regressors/gaussian_process_regressor.py:326: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  torch.range(0, self.y_tr_sigma_diag.shape[0] - 1)[None, :],
Traceback (most recent call last):
  File "scripts/semi_supervised/learning_curve_semi.py", line 237, in <module>
    train_and_test_semi_supervised(net, optimizer, train_semi, train_labeled, test_labeled, args.n_epochs)
  File "scripts/semi_supervised/learning_curve_semi.py", line 191, in train_and_test_semi_supervised
    train_results = train_metrics.test()
  File "/home/nguyenm5/coding/pinot/pinot/app/experiment.py", line 213, in test
    metric(
  File "/home/nguyenm5/coding/pinot/pinot/metrics.py", line 85, in r2
    return _r2(y, y_hat)
  File "/home/nguyenm5/coding/pinot/pinot/metrics.py", line 67, in _r2
    assert y.shape == y_hat.shape
AssertionError
Using backend: pytorch
/home/nguyenm5/anaconda3/envs/pinot/lib/python3.8/site-packages/dgl/base.py:25: UserWarning: Currently adjacency_matrix() returns a matrix with destination as rows by default.  In 0.5 the result will have source as rows (i.e. transpose=True)
  warnings.warn(msg, warn_type)
/home/nguyenm5/coding/pinot/pinot/regressors/gaussian_process_regressor.py:325: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  torch.range(0, self.y_tr_sigma_diag.shape[0] - 1)[:, None],
/home/nguyenm5/coding/pinot/pinot/regressors/gaussian_process_regressor.py:326: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  torch.range(0, self.y_tr_sigma_diag.shape[0] - 1)[None, :],
Traceback (most recent call last):
  File "scripts/semi_supervised/learning_curve_semi.py", line 237, in <module>
    train_and_test_semi_supervised(net, optimizer, train_semi, train_labeled, test_labeled, args.n_epochs)
  File "scripts/semi_supervised/learning_curve_semi.py", line 191, in train_and_test_semi_supervised
    train_results = train_metrics.test()
  File "/home/nguyenm5/coding/pinot/pinot/app/experiment.py", line 213, in test
    metric(
  File "/home/nguyenm5/coding/pinot/pinot/metrics.py", line 85, in r2
    return _r2(y, y_hat)
  File "/home/nguyenm5/coding/pinot/pinot/metrics.py", line 67, in _r2
    assert y.shape == y_hat.shape
AssertionError
Using backend: pytorch
/home/nguyenm5/anaconda3/envs/pinot/lib/python3.8/site-packages/dgl/base.py:25: UserWarning: Currently adjacency_matrix() returns a matrix with destination as rows by default.  In 0.5 the result will have source as rows (i.e. transpose=True)
  warnings.warn(msg, warn_type)
/home/nguyenm5/coding/pinot/pinot/regressors/gaussian_process_regressor.py:325: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  torch.range(0, self.y_tr_sigma_diag.shape[0] - 1)[:, None],
/home/nguyenm5/coding/pinot/pinot/regressors/gaussian_process_regressor.py:326: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  torch.range(0, self.y_tr_sigma_diag.shape[0] - 1)[None, :],
Traceback (most recent call last):
  File "scripts/semi_supervised/learning_curve_semi.py", line 237, in <module>
    train_and_test_semi_supervised(net, optimizer, train_semi, train_labeled, test_labeled, args.n_epochs)
  File "scripts/semi_supervised/learning_curve_semi.py", line 191, in train_and_test_semi_supervised
    train_results = train_metrics.test()
  File "/home/nguyenm5/coding/pinot/pinot/app/experiment.py", line 213, in test
    metric(
  File "/home/nguyenm5/coding/pinot/pinot/metrics.py", line 87, in r2
    return _r2(y, y_hat)
  File "/home/nguyenm5/coding/pinot/pinot/metrics.py", line 70, in _r2
    assert y.dim() == 2
AssertionError
Using backend: pytorch
/home/nguyenm5/anaconda3/envs/pinot/lib/python3.8/site-packages/dgl/base.py:25: UserWarning: Currently adjacency_matrix() returns a matrix with destination as rows by default.  In 0.5 the result will have source as rows (i.e. transpose=True)
  warnings.warn(msg, warn_type)
/home/nguyenm5/coding/pinot/pinot/regressors/gaussian_process_regressor.py:325: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  torch.range(0, self.y_tr_sigma_diag.shape[0] - 1)[:, None],
/home/nguyenm5/coding/pinot/pinot/regressors/gaussian_process_regressor.py:326: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  torch.range(0, self.y_tr_sigma_diag.shape[0] - 1)[None, :],
Traceback (most recent call last):
  File "scripts/semi_supervised/learning_curve_semi.py", line 237, in <module>
    train_and_test_semi_supervised(net, optimizer, train_semi, train_labeled, test_labeled, args.n_epochs)
  File "scripts/semi_supervised/learning_curve_semi.py", line 191, in train_and_test_semi_supervised
    train_results = train_metrics.test()
  File "/home/nguyenm5/coding/pinot/pinot/app/experiment.py", line 213, in test
    metric(
  File "/home/nguyenm5/coding/pinot/pinot/metrics.py", line 87, in r2
    return _r2(y, y_hat)
  File "/home/nguyenm5/coding/pinot/pinot/metrics.py", line 70, in _r2
    assert y.dim() == 2
AssertionError
Using backend: pytorch
/home/nguyenm5/anaconda3/envs/pinot/lib/python3.8/site-packages/dgl/base.py:25: UserWarning: Currently adjacency_matrix() returns a matrix with destination as rows by default.  In 0.5 the result will have source as rows (i.e. transpose=True)
  warnings.warn(msg, warn_type)
/home/nguyenm5/coding/pinot/pinot/regressors/gaussian_process_regressor.py:325: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  torch.range(0, self.y_tr_sigma_diag.shape[0] - 1)[:, None],
/home/nguyenm5/coding/pinot/pinot/regressors/gaussian_process_regressor.py:326: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  torch.range(0, self.y_tr_sigma_diag.shape[0] - 1)[None, :],
/home/nguyenm5/coding/pinot/pinot/metrics.py:45: UserWarning: Using a target size (torch.Size([299, 1])) that is different to the input size (torch.Size([299])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return torch.nn.functional.mse_loss(y, y_hat).pow(0.5)
/home/nguyenm5/coding/pinot/pinot/metrics.py:45: UserWarning: Using a target size (torch.Size([74, 1])) that is different to the input size (torch.Size([74])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return torch.nn.functional.mse_loss(y, y_hat).pow(0.5)
Traceback (most recent call last):
  File "scripts/semi_supervised/learning_curve_semi.py", line 241, in <module>
    "Finished training architecture = {} with regressor = {}, after {} seconds".format(architecture,\
NameError: name 'architecture' is not defined
Using backend: pytorch
/home/nguyenm5/anaconda3/envs/pinot/lib/python3.8/site-packages/dgl/base.py:25: UserWarning: Currently adjacency_matrix() returns a matrix with destination as rows by default.  In 0.5 the result will have source as rows (i.e. transpose=True)
  warnings.warn(msg, warn_type)
/home/nguyenm5/coding/pinot/pinot/regressors/gaussian_process_regressor.py:325: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  torch.range(0, self.y_tr_sigma_diag.shape[0] - 1)[:, None],
/home/nguyenm5/coding/pinot/pinot/regressors/gaussian_process_regressor.py:326: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  torch.range(0, self.y_tr_sigma_diag.shape[0] - 1)[None, :],
/home/nguyenm5/coding/pinot/pinot/metrics.py:45: UserWarning: Using a target size (torch.Size([299, 1])) that is different to the input size (torch.Size([299])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return torch.nn.functional.mse_loss(y, y_hat).pow(0.5)
/home/nguyenm5/coding/pinot/pinot/metrics.py:45: UserWarning: Using a target size (torch.Size([74, 1])) that is different to the input size (torch.Size([74])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return torch.nn.functional.mse_loss(y, y_hat).pow(0.5)
Traceback (most recent call last):
  File "scripts/semi_supervised/learning_curve_semi.py", line 241, in <module>
    "Finished training architecture = {} with regressor = {}, after {} seconds".format(architecture,\
NameError: name 'architecture' is not defined
