Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/plotting_active.py", line 323, in <module>
    
  File "scripts/active/plotting_active.py", line 71, in generate
    final_results = self.run_trials(ds)
  File "scripts/active/plotting_active.py", line 160, in run_trials
    # run experiment
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 412, in run
    
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 359, in acquire
    
RuntimeError: invalid argument 5: k not in range for dimension at /opt/conda/conda-bld/pytorch_1591914743399/work/aten/src/THC/generic/THCTensorTopK.cu:23
